# Generated by Django 5.0.6 on 2024-11-13 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lookups", "0001_initial"),
        ("questionbank", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=10)),
                ("abbreviation", models.CharField(blank=True, max_length=10)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("total_marks", models.PositiveIntegerField(default=0)),
                ("pass_marks", models.PositiveIntegerField(default=0)),
                ("exam_status", models.CharField(choices=[("draft", "Draft"), ("active", "Active")], default="draft", max_length=100)),
                ("is_public", models.BooleanField(default=False)),
                ("is_global", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("education_level", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.educationlevel")),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_exams",
                        to="lookups.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamSubject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_admin.exam")),
                ("subject_education_level", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.subjecteducationlevel")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_admin_examsubject",
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="subjects",
            field=models.ManyToManyField(through="exam_admin.ExamSubject", to="questionbank.subjecteducationlevel"),
        ),
        migrations.CreateModel(
            name="ExamSubjectCountry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lookups.country")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "exam_subject",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subject_countries", to="exam_admin.examsubject"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_admin_examsubject_country",
            },
        ),
        migrations.CreateModel(
            name="ExamSubjectQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("total_marks", models.PositiveIntegerField(default=0)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("exam_subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_admin.examsubject")),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.question")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_admin_examsubject_question",
            },
        ),
        migrations.AddField(
            model_name="examsubject",
            name="questions",
            field=models.ManyToManyField(through="exam_admin.ExamSubjectQuestion", to="questionbank.question"),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("waiting_duration", models.PositiveIntegerField(null=True)),
                ("extra_duration", models.PositiveIntegerField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_schedules",
                        to="lookups.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("time_limit", models.PositiveIntegerField(null=True)),
                ("is_global", models.BooleanField(default=True)),
                ("is_shuffle", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="exam_admin.exam")),
                (
                    "measuring_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sections_measuring_unit", to="lookups.measuringunit"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="examsubjectquestion",
            name="section",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="exam_admin.section"),
        ),
        migrations.CreateModel(
            name="SubSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("time_limit", models.PositiveIntegerField(null=True)),
                ("is_global", models.BooleanField(default=True)),
                ("is_shuffle", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "measuring_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subsections_measuring_unit", to="lookups.measuringunit"
                    ),
                ),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subsections", to="exam_admin.section")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="examsubjectquestion",
            name="subsection",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="exam_admin.subsection"),
        ),
    ]
