# Generated by Django 5.0.6 on 2024-11-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_admin", "0001_initial"),
        ("lookups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="organization",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="organization_schedules", to="lookups.organization"
            ),
        ),
    ]
