# Generated by Django 4.2.4 on 2025-01-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam_admin", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="pass_marks",
            new_name="passing_percentage",
        ),
    ]
