# Generated by Django 4.2.4 on 2025-01-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0002_organization_url"),
        ("questionbank", "0002_alter_question_title"),
        ("exam_admin", "0002_rename_pass_marks_exam_passing_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="education_level",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="questionbank.educationlevel"),
        ),
        migrations.AlterField(
            model_name="examsubjectquestion",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="questionbank.question"),
        ),
        migrations.AlterField(
            model_name="section",
            name="measuring_unit",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sections_measuring_unit", to="lookups.measuringunit"),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="measuring_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="subsections_measuring_unit", to="lookups.measuringunit"
            ),
        ),
    ]
