# Generated by Django 5.0.6 on 2024-11-05 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lookups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationPackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("users", models.PositiveIntegerField(default=0)),
                ("questions", models.PositiveIntegerField(default=0)),
                ("exams", models.PositiveIntegerField(default=0)),
                ("prep_exams", models.PositiveIntegerField(default=0)),
                ("exam_attempts", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="organization_packages", to="lookups.organization"),
                ),
                ("package", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lookups.package")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "organization_organization_package",
            },
        ),
        migrations.CreateModel(
            name="OrganizationUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="organization_users", to="lookups.organization"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_organizations", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "organization_organization_user",
            },
        ),
    ]
