# Generated by Django 5.0.6 on 2024-10-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="encryption_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
