# Generated by Django 5.0.6 on 2024-11-13 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam_public", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateExamSectionScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("total_obtainable_marks", models.IntegerField(default=0)),
                ("subsection_count", models.PositiveIntegerField(default=0)),
                ("score", models.FloatField(default=0)),
                ("candidate_exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_public.candidateexam")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "section_backlog",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name="section_scores", to="exam_public.sectionbacklog"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_scoring_candidateexam_sectionbacklog_score",
            },
        ),
        migrations.CreateModel(
            name="CandidateExamSubSectionScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("total_obtainable_marks", models.IntegerField(default=0)),
                ("score", models.FloatField(default=0)),
                ("candidate_exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_public.candidateexam")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "subsection_backlog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="subsection_scores", to="exam_public.subsectionbacklog"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_scoring_candidateexam_subsectionbacklog_score",
            },
        ),
    ]
