# Generated by Django 5.0.6 on 2024-10-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="permission",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="permission_resources", to="user.permission"
            ),
        ),
        migrations.DeleteModel(
            name="RoleResource",
        ),
    ]
