# Generated by Django 5.0.6 on 2024-07-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='status',
            new_name='meta_status',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='created_by',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='updated_by',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
