# Generated by Django 5.0.6 on 2024-07-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_status_baseuser_meta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='created_by',
            field=models.CharField(default='system', max_length=32),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='updated_by',
            field=models.CharField(default='system', max_length=32),
        ),
    ]
