# Generated by Django 4.2.4 on 2025-01-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_baseuser_otp_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="creation_context",
            field=models.CharField(
                choices=[("self", "Self"), ("facebook", "Facebook"), ("google", "Google"), ("public_exam", "Public Exam")],
                default="self",
                max_length=20,
                verbose_name="creation context",
            ),
        ),
    ]
