# Generated by Django 5.0.6 on 2024-07-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_baseuser_created_by_alter_baseuser_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
