# Generated by Django 5.0.6 on 2024-07-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_permission_role_baseuser_is_verified_baseuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='user.permission'),
        ),
    ]
