# Generated by Django 5.0.6 on 2024-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
