# Generated by Django 5.0.6 on 2024-07-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0008_alter_currency_symbol'),
        ('user', '0007_baseuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookups.country'),
        ),
    ]
