"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import sentry_sdk
from decouple import config

if int(config("ENABLE_SENTRY")):
    sentry_sdk.init(
        dsn=config("SENTRY_DSN"),
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        traces_sample_rate=1.0,
        # Set profiles_sample_rate to 1.0 to profile 100%
        # of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=1.0,
    )

# ---------------------------------------------------------------------------- #
#                                SYSTEM SETTINGS                               #
# ---------------------------------------------------------------------------- #
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (True if config("ENV") != "production" else False,)  #! SECURITY WARNING: don't run with debug turned on in production!


DATA_UPLOAD_MAX_MEMORY_SIZE = 128000000
ROOT_URLCONF = "core.urls"
WSGI_APPLICATION = "core.wsgi.application"
EMAIL_BACKEND = "django_ses.SESBackend"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

#! SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = config("APP_KEY")

    if not SECRET_KEY:
        os.environ["SIGN_KEY_DJANGO"] = SECRET_KEY  # type: ignore
        print("### >> Please specify 'APP_KEY' value before proceeding forward!!")
        exit(0)
except:
    print("### >> Please specify 'APP_KEY' variable in '.env' before proceeding forward!!")
    exit(0)

# ---------------------------------------------------------------------------- #
#                                     AUTH                                     #
# ---------------------------------------------------------------------------- #

REFRESH_TOKEN_VALIDITY = int(config("REFRESH_TOKEN_VALIDITY")) if config("REFRESH_TOKEN_VALIDITY") else 1
ACCESS_TOKEN_VALIDITY = int(config("ACCESS_TOKEN_VALIDITY")) if config("ACCESS_TOKEN_VALIDITY") else 150
AUTH_USER_MODEL = "user.BaseUser"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": SECRET_KEY,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# ---------------------------------------------------------------------------- #
#                                     CORS                                     #
# ---------------------------------------------------------------------------- #

ALLOWED_HOSTS = ["*"]
CORS_ALLOW_ALL_ORIGINS = True

# ---------------------------------------------------------------------------- #
#                                     SILK                                     #
# ---------------------------------------------------------------------------- #

SILKY_PYTHON_PROFILER = False
SILKY_PYTHON_PROFILER_BINARY = False
SILKY_META = False
SILKY_PYTHON_PROFILER_RESULT_PATH = "profiling"

if not os.path.exists(SILKY_PYTHON_PROFILER_RESULT_PATH):
    os.mkdir(SILKY_PYTHON_PROFILER_RESULT_PATH)

# ---------------------------------------------------------------------------- #
#                                      AWS                                     #
# ---------------------------------------------------------------------------- #

AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
AWS_QUERYSTRING_AUTH = True
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}
try:
    os.environ["AWS_ACCESS_KEY_ID"] = config("AWS_ACCESS_KEY_ID")  # type: ignore
    os.environ["AWS_SECRET_ACCESS_KEY"] = config("AWS_SECRET_ACCESS_KEY")  # type: ignore
    os.environ["AWS_DEFAULT_REGION"] = config("AWS_DEFAULT_REGION")  # type: ignore
except:
    pass

# ---------------------------------------------------------------------------- #
#                                INTERNALIZATION                               #
# ---------------------------------------------------------------------------- #
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
# USE_TZ = config("TZ_ACTIVE", default=True, cast=bool)
USE_TZ = 1

# ---------------------------------------------------------------------------- #
#                                     APPS                                     #
# ---------------------------------------------------------------------------- #


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    # * System
    "ping",
    "apps.lookups",
    "apps.user",
    "apps.organization",
    "apps.questionbank",
    "apps.exam_admin",
    "apps.exam_public",
    "apps.exam_scoring",
]
if DEBUG:
    INSTALLED_APPS += [
        "silk",
    ]

# ---------------------------------------------------------------------------- #
#                                REST FRAMEWORK                                #
# ---------------------------------------------------------------------------- #


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # "DEFAULT_PERMISSION_CLASSES": [
    #     "rest_framework.permissions.IsAuthenticated",
    # ],
    "DEFAULT_PERMISSION_CLASSES": ["custom.custom_permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
}

if DEBUG:
    # ? These permission classes are required for the browsable API, but they are not required for production.
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] += (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    )
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "core.middlewares.current_user_middleware.CurrentUserMiddleware",
    "core.middlewares.response_middleware.ResponseMiddleware",
]
if DEBUG:
    MIDDLEWARE += [
        "silk.middleware.SilkyMiddleware",
    ]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ---------------------------------------------------------------------------- #
#                                   DATABASE                                   #
# ---------------------------------------------------------------------------- #

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USERNAME"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
        # "OPTIONS": {"init_command": "SET sql_mode='STRICT_TRANS_TABLES'"},
        # "ATOMIC_REQUESTS": True,
    }
}

# ---------------------------------------------------------------------------- #
#                                   FIXTURES                                   #
# ---------------------------------------------------------------------------- #
FIXTURE_DIRS = [
    BASE_DIR / "apps" / "lookups" / "seeds",
    BASE_DIR / "apps" / "lookups" / "tests" / "seeds",
    BASE_DIR / "apps" / "user" / "seeds",
    BASE_DIR / "apps" / "questionbank" / "seeds",
    BASE_DIR / "apps" / "exam_admin" / "seeds",
    BASE_DIR / "apps" / "exam_public" / "seeds",
    BASE_DIR / "apps" / "organization" / "seeds",
    BASE_DIR / "apps" / "exam_scoring" / "seeds",
]
