# Generated by Django 5.0.6 on 2024-10-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam_admin", "0001_initial"),
        ("lookups", "0001_initial"),
        ("organization", "0001_initial"),
        ("questionbank", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_candidates",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_candidates", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "exam_public_candidate",
            },
        ),
        migrations.CreateModel(
            name="CandidateExam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("candidate_email", models.EmailField(max_length=254)),
                ("total_obtainable_marks", models.FloatField(blank=True, null=True)),
                ("obtained_marks", models.FloatField(blank=True, null=True)),
                ("exam_duration", models.PositiveIntegerField(null=True)),
                (
                    "exam_status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("attempted", "Attempted"),
                            ("submitted", "Submitted"),
                            ("marked", "Marked"),
                            ("scored", "Scored"),
                        ],
                        default="assigned",
                        max_length=100,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("waiting_duration", models.PositiveIntegerField(null=True)),
                ("extra_duration", models.PositiveIntegerField(null=True)),
                ("is_preparatory", models.BooleanField(default=False)),
                ("candidate", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="exam_public.candidate")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("schedule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_admin.schedule")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateExamAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("exam_backlog_question_choice_title", models.TextField(blank=True, null=True)),
                ("answer_text", models.TextField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("seconds_taken", models.IntegerField(default=0)),
                ("is_attempted", models.BooleanField(default=True)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "candidate_exam",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="exam_answers", to="exam_public.candidateexam"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_candidateexam_answer",
            },
        ),
        migrations.CreateModel(
            name="CandidateExamAnswerMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("candidate_exam_answer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_public.candidateexamanswer")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("media", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.media")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_candidateexam_answer_media",
            },
        ),
        migrations.AddField(
            model_name="candidateexamanswer",
            name="answer_files",
            field=models.ManyToManyField(through="exam_public.CandidateExamAnswerMedia", to="user.media"),
        ),
        migrations.CreateModel(
            name="CandidateExamStatusLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("exam_status", models.CharField(max_length=100)),
                (
                    "candidate_exam",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_logs", to="exam_public.candidateexam"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_candidateexam_statuslog",
            },
        ),
        migrations.CreateModel(
            name="ExamBacklog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=10)),
                ("abbreviation", models.CharField(blank=True, max_length=10)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("education_level_name", models.CharField(max_length=255)),
                ("total_marks", models.PositiveIntegerField(default=0)),
                ("pass_marks", models.PositiveIntegerField(default=0)),
                ("is_global", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("education_level", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="questionbank.educationlevel")),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="exam_admin.exam")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidateexam",
            name="exam_backlog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="candiate_exam_examsbacklog", to="exam_public.exambacklog"
            ),
        ),
        migrations.CreateModel(
            name="ExamBacklogQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("subject_name", models.CharField(max_length=255)),
                ("education_level_name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True, null=True)),
                ("max_retries", models.IntegerField(default=0)),
                ("retry_penalty", models.IntegerField(default=0)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("time_limit", models.IntegerField(default=0)),
                ("total_marks", models.IntegerField(default=0)),
                ("can_shuffle", models.BooleanField(default=False)),
                ("is_optional", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("is_global", models.BooleanField(default=False)),
                ("has_media", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("difficulty_level", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="questionbank.difficultylevel")),
                ("education_level", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="questionbank.educationlevel")),
                (
                    "exam_backlog",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="backlog_questions", to="exam_public.exambacklog"),
                ),
                ("measuring_unit", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="lookups.measuringunit")),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="questionbank.question")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="questionbank.subject")),
                ("type", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="questionbank.questiontype")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_exambacklog_question",
            },
        ),
        migrations.AddField(
            model_name="candidateexamanswer",
            name="exam_backlog_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="question_answers", to="exam_public.exambacklogquestion"
            ),
        ),
        migrations.CreateModel(
            name="ExamBacklogQuestionAttemptResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("wrong", "Wrong"),
                            ("partial", "Partial"),
                            ("skipped", "Skipped"),
                            ("unanswered", "Unanswered"),
                        ],
                        default="unanswered",
                        max_length=100,
                    ),
                ),
                ("attempt_response", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="questionbank.questionattemptresponse")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "exam_backlog_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="backlog_attempt_responses", to="exam_public.exambacklogquestion"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_exambacklog_question_attemptresponse",
            },
        ),
        migrations.CreateModel(
            name="ExamBacklogQuestionChoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True, null=True)),
                ("weight", models.IntegerField(default=0)),
                ("is_negative_weight", models.BooleanField(default=False)),
                ("is_correct", models.BooleanField(default=False)),
                ("has_media", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "exam_backlog_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="backlog_choices", to="exam_public.exambacklogquestion"
                    ),
                ),
                ("question_choice", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="questionbank.questionchoice")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_exambacklog_question_choice",
            },
        ),
        migrations.AddField(
            model_name="candidateexamanswer",
            name="exam_backlog_question_choice",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="exam_public.exambacklogquestionchoice"),
        ),
        migrations.CreateModel(
            name="ExamBacklogQuestionChoiceMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "exam_backlog_question_choice",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_public.exambacklogquestionchoice"),
                ),
                ("media", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="user.media")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_exambacklog_question_choice_media",
            },
        ),
        migrations.AddField(
            model_name="exambacklogquestionchoice",
            name="medias",
            field=models.ManyToManyField(through="exam_public.ExamBacklogQuestionChoiceMedia", to="user.media"),
        ),
        migrations.CreateModel(
            name="ExamBacklogQuestionCountry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lookups.country")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("exam_backlog_question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_public.exambacklogquestion")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_exambacklog_question_country",
            },
        ),
        migrations.AddField(
            model_name="exambacklogquestion",
            name="countries",
            field=models.ManyToManyField(through="exam_public.ExamBacklogQuestionCountry", to="lookups.country"),
        ),
        migrations.CreateModel(
            name="ExamBacklogQuestionMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("exam_backlog_question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_public.exambacklogquestion")),
                ("media", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="user.media")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_exambacklog_question_media",
            },
        ),
        migrations.AddField(
            model_name="exambacklogquestion",
            name="medias",
            field=models.ManyToManyField(through="exam_public.ExamBacklogQuestionMedia", to="user.media"),
        ),
        migrations.CreateModel(
            name="ExamBacklogQuestionRetryHint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("sequence", models.IntegerField(default=1)),
                ("has_media", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "exam_backlog_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="backlog_retry_hints", to="exam_public.exambacklogquestion"
                    ),
                ),
                ("retry_hint", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="questionbank.questionretryhint")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_exambacklog_question_retryhint",
            },
        ),
        migrations.CreateModel(
            name="CandidateExamRetryhint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("penalty_score", models.DecimalField(decimal_places=1, max_digits=10)),
                (
                    "candidate_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="candidate_exam_retry_hints", to="exam_public.candidateexam"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "exam_backlog_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="question_fetched_retry_hints", to="exam_public.exambacklogquestion"
                    ),
                ),
                (
                    "exam_backlog_question_retry_hint",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_public.exambacklogquestionretryhint"),
                ),
            ],
            options={
                "db_table": "exam_public_candidateexam_retryhint",
            },
        ),
        migrations.CreateModel(
            name="ExamBacklogQuestionRetryHintMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "exam_backlog_question_retry_hint",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_public.exambacklogquestionretryhint"),
                ),
                ("media", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="user.media")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_exambacklog_question_retryhint_media",
            },
        ),
        migrations.AddField(
            model_name="exambacklogquestionretryhint",
            name="medias",
            field=models.ManyToManyField(through="exam_public.ExamBacklogQuestionRetryHintMedia", to="user.media"),
        ),
        migrations.CreateModel(
            name="ExamBacklogQuestionTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "exam_backlog_question",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="backlog_tags", to="exam_public.exambacklogquestion"),
                ),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="questionbank.tag")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_exambacklog_question_tag",
            },
        ),
        migrations.CreateModel(
            name="SectionBacklog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("time_limit", models.PositiveIntegerField(null=True)),
                ("is_global", models.BooleanField(default=True)),
                ("is_shuffle", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "exam_backlog",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="section_backlogs", to="exam_public.exambacklog"),
                ),
                ("measuring_unit", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="lookups.measuringunit")),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="exam_admin.section")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_sectionbacklog",
            },
        ),
        migrations.AddField(
            model_name="exambacklogquestion",
            name="section_backlog",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="exam_public.sectionbacklog"),
        ),
        migrations.CreateModel(
            name="SubSectionBacklog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("time_limit", models.PositiveIntegerField(null=True)),
                ("is_global", models.BooleanField(default=True)),
                ("is_shuffle", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("exam_backlog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_public.exambacklog")),
                ("measuring_unit", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="lookups.measuringunit")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="subsection_backlogs", to="exam_public.sectionbacklog"
                    ),
                ),
                ("subsection", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="exam_admin.subsection")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_subsectionbacklog",
            },
        ),
        migrations.AddField(
            model_name="exambacklogquestion",
            name="subsection_backlog",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="exam_public.subsectionbacklog"),
        ),
    ]
