# Generated by Django 5.0.6 on 2024-12-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_public", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateexam",
            name="exam_backlog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="candidate_exam_examsbacklog", to="exam_public.exambacklog"
            ),
        ),
    ]
