# Generated by Django 4.2.4 on 2025-01-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_public", "0002_alter_candidateexam_exam_backlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateexam",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
