# Generated by Django 4.2.4 on 2025-01-03 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exam_admin", "0001_initial"),
        ("exam_public", "0003_candidateexam_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateexam",
            name="extra_duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidateexam",
            name="schedule",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="exam_admin.schedule"),
        ),
        migrations.AlterField(
            model_name="candidateexam",
            name="waiting_duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ExamBacklogExaminer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("exam_backlog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="exam_public.exambacklog")),
                ("examiner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_public_exambacklog_examiner",
            },
        ),
        migrations.AddField(
            model_name="exambacklog",
            name="examiners",
            field=models.ManyToManyField(through="exam_public.ExamBacklogExaminer", to=settings.AUTH_USER_MODEL),
        ),
    ]
