# Generated by Django 4.2.4 on 2025-01-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_public", "0004_alter_candidateexam_extra_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateexam",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidateexam",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
