# Generated by Django 4.2.4 on 2025-01-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_public", "0005_alter_candidateexam_end_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateexam",
            name="exam_questions_visibility",
            field=models.CharField(choices=[("all_at_once", "All at Once"), ("one_by_one", "One by One")], default="all_at_once", max_length=100),
        ),
    ]
