# Generated by Django 4.2.4 on 2025-01-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_public", "0006_candidateexam_exam_questions_visibility"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exambacklog",
            old_name="pass_marks",
            new_name="passing_percentage",
        ),
        migrations.AddField(
            model_name="candidateexam",
            name="exam_result",
            field=models.CharField(choices=[("pass", "Pass"), ("fail", "Fail"), ("pending", "Pending")], default="pending", max_length=100),
        ),
        migrations.AlterField(
            model_name="candidateexam",
            name="exam_status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("attempted", "Attempted"),
                    ("submitted", "Submitted"),
                    ("marked", "Marked"),
                    ("scored", "Scored"),
                    ("expired", "Expired"),
                ],
                default="assigned",
                max_length=100,
            ),
        ),
    ]
