# Generated by Django 4.2.4 on 2025-01-13 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0002_organization_url"),
        ("exam_public", "0007_rename_pass_marks_exambacklog_passing_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateexam",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="lookups.organization"),
        ),
    ]
