# Generated by Django 4.2.4 on 2025-01-28 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam_admin", "0002_rename_pass_marks_exam_passing_percentage"),
        ("exam_public", "0008_candidateexam_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateexam",
            name="schedule",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="exam_admin.schedule"),
        ),
    ]
