# Generated by Django 4.2.4 on 2025-01-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_public", "0009_alter_candidateexam_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exambacklogquestion",
            name="title",
            field=models.TextField(),
        ),
    ]
