# Generated by Django 4.2.4 on 2025-02-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_public", "0010_alter_exambacklogquestion_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateexam",
            name="is_created_by_candidate",
            field=models.BooleanField(default=False),
        ),
    ]
