# Generated by Django 4.2.4 on 2025-02-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_public", "0011_candidateexam_is_created_by_candidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="is_self_preparation_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidate",
            name="self_exam_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidate",
            name="self_exam_creation_limit",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
