# Generated by Django 5.0.6 on 2024-10-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lookups", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=10)),
                ("sequence", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True, null=True)),
                ("max_retries", models.IntegerField(default=0)),
                ("retry_penalty", models.IntegerField(default=0)),
                ("can_shuffle", models.BooleanField(default=False)),
                ("has_media", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAttemptResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("wrong", "Wrong"),
                            ("partial", "Partial"),
                            ("skipped", "Skipped"),
                            ("unanswered", "Unanswered"),
                        ],
                        default="unanswered",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempt_responses", to="questionbank.question"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True, null=True)),
                ("weight", models.IntegerField(default=0)),
                ("is_negative_weight", models.BooleanField(default=False)),
                ("is_correct", models.BooleanField(default=False)),
                ("has_media", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="choices", to="questionbank.question")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionChoiceMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("media", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.media")),
                ("question_choice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.questionchoice")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "questionbank_questionchoice_media",
            },
        ),
        migrations.AddField(
            model_name="questionchoice",
            name="medias",
            field=models.ManyToManyField(related_name="choices", through="questionbank.QuestionChoiceMedia", to="user.media"),
        ),
        migrations.CreateModel(
            name="QuestionMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("media", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.media")),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.question")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "questionbank_question_media",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="medias",
            field=models.ManyToManyField(related_name="questions", through="questionbank.QuestionMedia", to="user.media"),
        ),
        migrations.CreateModel(
            name="QuestionRetryHint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("sequence", models.IntegerField(default=1)),
                ("has_media", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="retry_hints", to="questionbank.question")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionRetryHintMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("media", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.media")),
                ("question_retry_hint", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.questionretryhint")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "questionbank_questionretryhint_media",
            },
        ),
        migrations.AddField(
            model_name="questionretryhint",
            name="medias",
            field=models.ManyToManyField(related_name="retry_hints", through="questionbank.QuestionRetryHintMedia", to="user.media"),
        ),
        migrations.CreateModel(
            name="QuestionSubject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("time_limit", models.IntegerField(default=0)),
                ("total_marks", models.IntegerField(default=0)),
                ("is_optional", models.BooleanField(default=False)),
                ("is_global", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("difficulty_level", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.difficultylevel")),
                ("measuring_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lookups.measuringunit")),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subjects", to="questionbank.question")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionSubjectCountry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lookups.country")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "question_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subject_countries", to="questionbank.questionsubject"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "questionbank_questionsubject_country",
            },
        ),
        migrations.AddField(
            model_name="questionsubject",
            name="countries",
            field=models.ManyToManyField(through="questionbank.QuestionSubjectCountry", to="lookups.country"),
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.questiontype"),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectEducationLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("education_level", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.educationlevel")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.subject")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "questionbank_subject_educationlevel",
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="education_levels",
            field=models.ManyToManyField(related_name="subjects", through="questionbank.SubjectEducationLevel", to="questionbank.educationlevel"),
        ),
        migrations.AddField(
            model_name="questionsubject",
            name="subject_education_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="question_subjects", to="questionbank.subjecteducationlevel"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="subject_education_levels",
            field=models.ManyToManyField(related_name="questions", through="questionbank.QuestionSubject", to="questionbank.subjecteducationlevel"),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.question")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questionbank.tag")),
            ],
            options={
                "db_table": "questionbank_question_tag",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(related_name="questions", through="questionbank.QuestionTag", to="questionbank.tag"),
        ),
        migrations.AlterUniqueTogether(
            name="questionsubject",
            unique_together={("question", "subject_education_level")},
        ),
    ]
