# Generated by Django 4.2.4 on 2025-01-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.TextField(),
        ),
    ]
