# Generated by Django 5.0.6 on 2024-11-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0001_initial"),
        ("questionbank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationlevel",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="lookups.organization"),
        ),
        migrations.AddField(
            model_name="subject",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="lookups.organization"),
        ),
        migrations.AddField(
            model_name="subjecteducationlevel",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="lookups.organization"),
        ),
    ]
