# Generated by Django 5.0.6 on 2024-11-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0002_educationlevel_organization_subject_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationlevel",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="educationlevel",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
