# Generated by Django 5.0.6 on 2024-11-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0001_initial"),
        ("questionbank", "0003_alter_educationlevel_code_alter_educationlevel_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="education_levels",
        ),
        migrations.AddField(
            model_name="tag",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="lookups.organization"),
        ),
    ]
