# Generated by Django 5.0.6 on 2024-12-30 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("to_email_list", models.TextField()),
                ("from_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed")], default="queued", max_length=50)),
                ("error", models.TextField(blank=True, null=True)),
                ("cc_list", models.EmailField(blank=True, max_length=254, null=True)),
                ("bcc_list", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "emails_emaillog",
            },
        ),
        migrations.CreateModel(
            name="EmailLogAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")], default="active", max_length=10
                    ),
                ),
                ("file", models.FileField(upload_to="email_attachments/")),
                ("name", models.CharField(max_length=255)),
                ("ext", models.CharField(max_length=10)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("email_log", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="emails.emaillog")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "emails_emaillog_attachment",
            },
        ),
    ]
