# Generated by Django 4.2.4 on 2024-12-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
