# Generated by Django 4.2.4 on 2025-01-29 05:37

import apps.lookups.models.lookup_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0002_organization_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=apps.lookups.models.lookup_models.upload_to),
        ),
    ]
