# Generated by Django 5.0.6 on 2024-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_currency_country_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='system', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='system', max_length=32)),
                ('meta_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='system', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='system', max_length=32)),
                ('meta_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.ManyToManyField(related_name='countries', to='lookups.currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(related_name='countries', to='lookups.language'),
        ),
        migrations.AddField(
            model_name='country',
            name='timezones',
            field=models.ManyToManyField(related_name='countries', to='lookups.timezone'),
        ),
    ]
