# Generated by Django 4.2.4 on 2025-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0003_organization_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="currencies",
            field=models.ManyToManyField(to="lookups.currency"),
        ),
        migrations.AlterField(
            model_name="country",
            name="languages",
            field=models.ManyToManyField(to="lookups.language"),
        ),
        migrations.AlterField(
            model_name="country",
            name="timezones",
            field=models.ManyToManyField(to="lookups.timezone"),
        ),
    ]
