# Generated by Django 5.0.6 on 2024-07-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0004_country_flag_country_is_un_member_country_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dial_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
