# Generated by Django 5.0.6 on 2024-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0006_remove_country_code_country_iso2_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
